dist: xenial                                                                                                                           
language: python
python:
  - "3.5.3"
  - "3.7"

install:
  - cd drpy
  - pip install -r test-requires.txt
  # Install Self
  - pip install -e .

script:
  - flake8
  - pytest -v -l --cov tests/

